import { getCorePreferences } from "./ledger.js";
import type { Preference, PreferenceLedger } from "./types.js";
import { assertValidPreferenceLedger } from "./validation.js";

function renderPreference(preference: Preference): string[] {
  const domains = preference.domains.join(", ");
  return [
    `## [w${preference.weight}] ${preference.id} (${domains})`,
    preference.statement,
    `_Apply:_ ${preference.apply}`,
    "",
  ];
}

/** Deterministically renders the always-on core from active core preferences. */
export function renderPreferenceCore(ledger: PreferenceLedger): string {
  assertValidPreferenceLedger(ledger);
  const lines = [
    "# OpenBrain Preferences Core (always-on)",
    "",
    "Generated from 10_memory/preferences/_ledger.json. Do not edit this file by hand.",
    "",
    "Apply these active core preferences to every substantive response. Scoped preferences remain available in the ledger for context-specific work.",
    "",
  ];

  for (const preference of getCorePreferences(ledger)) {
    lines.push(...renderPreference(preference));
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

export function renderPreferenceMirror(ledger: PreferenceLedger): string {
  const core = renderPreferenceCore(ledger).trimEnd();
  return [
    "## OpenBrain preference core",
    "",
    "The generated preferences below are authoritative for this vault.",
    "",
    core,
  ].join("\n");
}
