import { getCorePreferences } from "./ledger.js";
import type { Preference, PreferenceLedger } from "./types.js";
import { assertValidPreferenceLedger } from "./validation.js";

/**
 * The always-on core is paid in tokens on every session, so a line only earns
 * its place when it carries something the lines above do not. "why" is rendered
 * only when it differs from the statement: a preference created from a single
 * sentence has why, apply, and statement all equal to that sentence, and
 * printing it three times would cost context for no information. A preference
 * that came through the review gate carries a distinct rationale, and that one
 * is worth the room because it lets a model apply the rule to a case nobody
 * wrote down.
 */
function renderPreference(preference: Preference): string[] {
  const domains = preference.domains.join(", ");
  const lines = [
    `## [w${preference.weight}] ${preference.id} (${domains})`,
    preference.statement,
  ];
  if (preference.why.trim() !== preference.statement.trim()) {
    lines.push(`_Why:_ ${preference.why}`);
  }
  lines.push(`_Apply:_ ${preference.apply}`, "");
  return lines;
}

/** Deterministically renders the always-on core from active core preferences. */
export function renderPreferenceCore(ledger: PreferenceLedger): string {
  assertValidPreferenceLedger(ledger);
  const lines = [
    "# OpenBrain Preferences Core (always-on)",
    "",
    "Generated from 10_memory/preferences/_ledger.json. Do not edit this file by hand.",
    "",
    "Apply these active core preferences to every substantive response. Scoped preferences remain available in the ledger for context-specific work.",
    "",
  ];

  for (const preference of getCorePreferences(ledger)) {
    lines.push(...renderPreference(preference));
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

export function renderPreferenceMirror(ledger: PreferenceLedger): string {
  const core = renderPreferenceCore(ledger).trimEnd();
  return [
    "## OpenBrain preference core",
    "",
    "The generated preferences below are authoritative for this vault.",
    "",
    core,
  ].join("\n");
}
